import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// Entity pages cross-link each other. An EN page that links a bare RU route
// silently switches the reader's language, and the twins are generated by
// `pnpm translate`, which can keep the source link — so the check lives here.
const PAGES = {
  about: ["blog", "projects", "now", "uses"],
  now: ["about", "contact", "courses/claude-code-guide"],
  uses: ["projects/astro-blog", "contact"],
} as const;

describe.each(["ru", "en"] as const)("site entity pages (%s)", (locale) => {
  const prefix = locale === "en" ? "/en" : "";

  it.each(Object.entries(PAGES))("%s links related pages in the same locale", (page, routes) => {
    const md = readFileSync(join(process.cwd(), `src/content/site${prefix}/${page}.md`), "utf8");
    const body = md.replace(/^---[\s\S]*?---\r?\n/, "");

    for (const route of routes) expect(body).toContain(`](${prefix}/${route}/)`);
    if (locale === "en") expect(body).not.toMatch(/\]\(\/(?!en\/)[^)]+\)/);
  });
});
